server.port=8083
spring.h2.console.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username=embarkx
spring.datasource.password=embarkx
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect