server.port=8083
spring.h2.console.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
management.endpoints.web.exposure.include=*
#spring.rabbitmq.listener.simple.acknowledge-mode=AUTO
#spring.cloud.bus.enabled=true
#spring.cloud.bus.rabbit.declare-exchange=true
#spring.rabbitmq.dynamic=true
spring.cloud.stream.bindings.createOrder-out-0.destination=order.exchange
spring.cloud.stream.bindings.createOrder-out-0.content-type=application/json
#spring.cloud.stream.rabbit.bindings.createOrder-out-0.producer.routing-key-expression="'order.tracking'"
#KAFKA
spring.cloud.stream.default-binder=kafka
spring.cloud.stream.kafka.binder.brokers=localhost:9092

#rabbitmq.exchange.name=order.exchange
#rabbitmq.queue.name=order.queue
#rabbitmq.routing.key=order.tracking
app.message=HelloOrder
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
logging.file.name=logs/${spring.application.name}.log
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.max-history=7
management.tracing.sampling.probability=1.0
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.health.circuitbreakers.enabled=true
#CircuitBreaker
resilience4j.circuitbreaker.instances.productService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.productService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.productService.minimumNumberofCalls=5
resilience4j.circuitbreaker.instances.productService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.productService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.productService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.productService.slidingWindowType=count_based

#Retry breaker
resilience4j.retry.instances.retryBreaker.maxAttempts=5
resilience4j.retry.instances.retryBreaker.waitDuration=500ms

#Rate Limiter
resilience4j.ratelimiter.instances.rateBreaker.timeout-duration=0
resilience4j.ratelimiter.instances.rateBreaker.limit-refresh-period=4s
resilience4j.ratelimiter.instances.rateBreaker.limit-for-period=2