spring.application.name=product-service
server.port=8082
spring.h2.console.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
#spring.datasource.url=jdbc:postgresql://ep-shiny-cake-aqvfwr3e-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_4AodpxfQr7YR
spring.datasource.username=embarkx
spring.datasource.password=embarkx
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

